/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiView;

import java.util.Observable;
import java.util.Observer;
import javax.swing.ImageIcon;
import shoppinggui.IController;
import shoppinggui.Order;
import shoppinggui.OrderController;

/**
 *
 * @author kcheng
 */
public class HomeFrame extends javax.swing.JFrame implements Observer {

    ImageIcon shoesIcon;
    ImageIcon topIcon;
    ImageIcon bottomIcon;
    ImageIcon bagIcon;
    ImageIcon emptyCartIcon;
    ImageIcon shopCartIcon;
    ImageIcon colorPoloIcon;
    ImageIcon colorBottomIcon;
    ImageIcon colorBagIcon;
    ImageIcon colorShoesIcon;
    private Boolean hasOrderItem = false;
    private IController controller;
    private OrderController orderController ;
    private Order order;

    /**
     * Creates new form HomeFrame
     * @param ctrl
     */
    public HomeFrame(IController ctrl) {
        loadIcons();
        controller = ctrl;
        orderController = ctrl.getOrderController() ;
        this.order = orderController.getOrder() ;
        initComponents();
        panelProducts.setVisible(false);
        panelWelcome.setVisible(true);
        btnShoes.addActionListener(ctrl);
        btnAccessories.addActionListener(ctrl);
        btnBottom.addActionListener(ctrl);
        btnTop.addActionListener(ctrl);
        btnShoppingCart.addActionListener(ctrl);
        getPanelProducts().setOrderController(orderController);
        shoppingCartView.loadOrder(this.order);
        shoppingCartView.setController(controller);
        lblItemCount.setVisible(false);
        shoppingCartView.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeading = new javax.swing.JPanel();
        lblHeading = new javax.swing.JLabel();
        lbllogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelWest = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnShoes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnTop = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnBottom = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnAccessories = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblItemCount = new javax.swing.JLabel();
        btnShoppingCart = new javax.swing.JButton();
        panelCenter = new javax.swing.JPanel();
        panelWelcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelProducts = new guiView.PanelProducts();
        shoppingCartView = new guiView.PanelShoppingCartView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 630));

        panelHeading.setBackground(new java.awt.Color(0, 51, 204));
        panelHeading.setForeground(new java.awt.Color(204, 204, 255));

        lblHeading.setBackground(new java.awt.Color(102, 0, 102));
        lblHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(204, 204, 255));
        lblHeading.setText("Fashion Boutique Shopping Mall");

        lbllogo.setForeground(new java.awt.Color(255, 255, 255));
        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiView/adidas-78x51.png"))); // NOI18N
        lbllogo.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("adidas authorized retailer");

        javax.swing.GroupLayout panelHeadingLayout = new javax.swing.GroupLayout(panelHeading);
        panelHeading.setLayout(panelHeadingLayout);
        panelHeadingLayout.setHorizontalGroup(
            panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 661, Short.MAX_VALUE)
                .addGroup(panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadingLayout.createSequentialGroup()
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadingLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(146, 146, 146))))
        );
        panelHeadingLayout.setVerticalGroup(
            panelHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(lbllogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(panelHeading, java.awt.BorderLayout.PAGE_START);

        panelWest.setBackground(new java.awt.Color(153, 153, 153));
        panelWest.setPreferredSize(new java.awt.Dimension(100, 439));

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));

        btnShoes.setIcon(shoesIcon);
        btnShoes.setBorderPainted(false);
        btnShoes.setFocusPainted(false);
        btnShoes.setPreferredSize(new java.awt.Dimension(90, 80));
        btnShoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShoesMouseExited(evt);
            }
        });
        jPanel2.add(btnShoes);

        panelWest.add(jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        btnTop.setIcon(topIcon     );
        btnTop.setBorderPainted(false);
        btnTop.setFocusPainted(false);
        btnTop.setPreferredSize(new java.awt.Dimension(90, 80));
        btnTop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTopMouseExited(evt);
            }
        });
        jPanel3.add(btnTop);

        panelWest.add(jPanel3);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 100));

        btnBottom.setIcon(bottomIcon     );
        btnBottom.setBorderPainted(false);
        btnBottom.setFocusPainted(false);
        btnBottom.setPreferredSize(new java.awt.Dimension(90, 80));
        btnBottom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBottomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBottomMouseExited(evt);
            }
        });
        jPanel4.add(btnBottom);

        panelWest.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 100));

        btnAccessories.setIcon(bagIcon     );
        btnAccessories.setBorderPainted(false);
        btnAccessories.setFocusPainted(false);
        btnAccessories.setPreferredSize(new java.awt.Dimension(90, 80));
        btnAccessories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccessoriesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccessoriesMouseExited(evt);
            }
        });
        jPanel5.add(btnAccessories);

        panelWest.add(jPanel5);

        jPanel7.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblItemCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblItemCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemCount.setText("3");
        lblItemCount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 153, 0))); // NOI18N
        lblItemCount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblItemCount.setPreferredSize(new java.awt.Dimension(15, 15));
        jPanel7.add(lblItemCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 5, 30, 20));

        btnShoppingCart.setIcon(emptyCartIcon);
        btnShoppingCart.setBorderPainted(false);
        btnShoppingCart.setFocusPainted(false);
        btnShoppingCart.setOpaque(false);
        btnShoppingCart.setPreferredSize(new java.awt.Dimension(90, 80));
        btnShoppingCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShoppingCartActionPerformed(evt);
            }
        });
        jPanel7.add(btnShoppingCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        panelWest.add(jPanel7);

        getContentPane().add(panelWest, java.awt.BorderLayout.WEST);

        panelCenter.setLayout(new javax.swing.OverlayLayout(panelCenter));

        panelWelcome.setBackground(new java.awt.Color(204, 204, 255));
        panelWelcome.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Welcome to our shopping mall..");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("You can review the shopping cart and check out from there.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Please fee free to browser our product by clicking on the button on the left.");

        javax.swing.GroupLayout panelWelcomeLayout = new javax.swing.GroupLayout(panelWelcome);
        panelWelcome.setLayout(panelWelcomeLayout);
        panelWelcomeLayout.setHorizontalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelWelcomeLayout.setVerticalGroup(
            panelWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWelcomeLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        panelCenter.add(panelWelcome);

        panelProducts.setBackground(new java.awt.Color(204, 204, 255));
        panelProducts.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelCenter.add(panelProducts);
        panelCenter.add(shoppingCartView);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel3FocusGained

    private void btnShoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShoesMouseEntered
        // TODO add your handling code here:
        btnShoes.setIcon(colorShoesIcon);

    }//GEN-LAST:event_btnShoesMouseEntered

    private void btnTopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopMouseEntered
        btnTop.setIcon(colorPoloIcon);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTopMouseEntered

    private void btnTopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTopMouseExited
        // TODO add your handling code here:
        btnTop.setIcon(topIcon);
    }//GEN-LAST:event_btnTopMouseExited

    private void btnAccessoriesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccessoriesMouseEntered
        btnAccessories.setIcon(colorBagIcon);
    }//GEN-LAST:event_btnAccessoriesMouseEntered

    private void btnAccessoriesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccessoriesMouseExited
        // TODO add your handling code here:
        btnAccessories.setIcon(bagIcon);
    }//GEN-LAST:event_btnAccessoriesMouseExited

    private void btnBottomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBottomMouseExited
        // TODO add your handling code here:
        btnBottom.setIcon(bottomIcon);
    }//GEN-LAST:event_btnBottomMouseExited

    private void btnBottomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBottomMouseEntered
        // TODO add your handling code here:
        btnBottom.setIcon(colorBottomIcon);
    }//GEN-LAST:event_btnBottomMouseEntered

    private void btnShoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShoesMouseExited
        btnShoes.setIcon(shoesIcon);
    }//GEN-LAST:event_btnShoesMouseExited

    private void btnShoppingCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShoppingCartActionPerformed
        // TODO add your handling code here:
        panelWelcome.setVisible(false );
        panelProducts.setVisible(false);
        shoppingCartView.setVisible(true);
        shoppingCartView.reloadData();
    }//GEN-LAST:event_btnShoppingCartActionPerformed

    /**
     * @param args the command line arguments
     */
    private void loadIcons() {

        shoesIcon = new ImageIcon(".\\resources\\icons\\shoesicon.png");
        topIcon = new ImageIcon(".\\resources\\icons\\polo.png");
        bottomIcon = new ImageIcon(".\\resources\\icons\\shorts.png");
        bagIcon = new ImageIcon(".\\resources\\icons\\bags.png");
        shopCartIcon = new ImageIcon(".\\resources\\icons\\shoppingcart.png");
        emptyCartIcon = new ImageIcon(".\\resources\\icons\\emptycart.png");
        colorPoloIcon = new ImageIcon(".\\resources\\icons\\colorpolo.png");
        colorBottomIcon = new ImageIcon(".\\resources\\icons\\colorshorts.png");
        colorBagIcon = new ImageIcon(".\\resources\\icons\\colorbag.png");
        colorShoesIcon = new ImageIcon(".\\resources\\icons\\colorhighheels.png");

    }

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HomeFrame(new TestController()).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccessories;
    private javax.swing.JButton btnBottom;
    private javax.swing.JButton btnShoes;
    private javax.swing.JButton btnShoppingCart;
    private javax.swing.JButton btnTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblItemCount;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelHeading;
    private guiView.PanelProducts panelProducts;
    private javax.swing.JPanel panelWelcome;
    private javax.swing.JPanel panelWest;
    private guiView.PanelShoppingCartView shoppingCartView;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        // received notify from the the updated order 
        System.out.println("getting something back from observerable");
        if( o instanceof Order) {
            this.order = (Order) o ;
            
            updateShoppingCartButtonIcon() ;
            
        }
       
    }

    private void updateShoppingCartButtonIcon() {
        
        if( this.order.hasItem() ) {
            getBtnShoppingCart().setIcon(shopCartIcon);
            lblItemCount.setVisible(true);
            lblItemCount.setText( ((Integer) this.order.getOrderItems().size()).toString() );
        }
        else {
            getBtnShoppingCart().setIcon(emptyCartIcon);
            lblItemCount.setVisible(false);
            lblItemCount.setText("" ) ;
        }
        
    }
    
    /**
     * @return the btnAccessories
     */
    public javax.swing.JButton getBtnAccessories() {
        return btnAccessories;
    }

    /**
     * @param btnAccessories the btnAccessories to set
     */
    public void setBtnAccessories(javax.swing.JButton btnAccessories) {
        this.btnAccessories = btnAccessories;
    }

    /**
     * @return the btnBottom
     */
    public javax.swing.JButton getBtnBottom() {
        return btnBottom;
    }

    /**
     * @return the btnShoes
     */
    public javax.swing.JButton getBtnShoes() {
        return btnShoes;
    }

    /**
     * @return the btnShoppingCart
     */
    public javax.swing.JButton getBtnShoppingCart() {
        return btnShoppingCart;
    }

    /**
     * @return the btnTop
     */
    public javax.swing.JButton getBtnTop() {
        return btnTop;
    }

    /**
     * @return the panelProducts
     */
    public guiView.PanelProducts getPanelProducts() {
        return panelProducts;
    }

    /**
     * @return the panelWelcome
     */
    public javax.swing.JPanel getPanelWelcome() {
        return panelWelcome;
    }
    public javax.swing.JPanel getPanelShoppingCart() {
        return shoppingCartView;
    }
}
