/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiView;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.MediaTracker;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import shoppinggui.Clothing;
import shoppinggui.OrderController;
import shoppinggui.Product;

/**
 *
 * @author kcheng
 */
public class PanelOrder extends javax.swing.JPanel implements Runnable {

    private OrderController oc ;
    
    /**
     *
     * @return
     */
    public Integer getOrderedQty() {
        return (Integer) getSpnQty().getValue() ;
    }
    
    /**
     *
     * @return
     */
    public String getOrderedSize() {
        if(getCboSizes().getSelectedItem()== null)
            return "";
        return getCboSizes().getSelectedItem().toString() ;
    }
    
    /**
     *
     * @return
     */
    public String getOrderedColor() {
        if( getCboColor().getSelectedItem() == null)
            return "" ;
        
        return getCboColor().getSelectedItem().toString() ;
    }
    
    /**
     *
     * @return
     */
    public Product getProduct() {
        return this.product ;
    }
    
    /**
     *
     * @return
     */
    public JButton getCloseButton() {
        return btnClose ;
    }
    
    /**
     *
     * @return
     */
    public JComboBox getCboSizes() {
        return cboSize ;
    }

    /**
     *
     * @return
     */
    public JComboBox getCboColor() {
        return cboColor ;
    }
    
    /**
     *
     * @return
     */
    public JSpinner getSpnQty() {
        return spnQty ;
    }
    
    /**
     *
     * @return
     */
    public JButton getbtnAdd() {
        return btnAdd ;
    }
    /**
     * @return the sizes
     */
    public String[] getSizes() {
        return sizes;
    }

    /**
     * @param sizes the sizes to set
     */
    public void setSizes(String[] sizes) {
        this.sizes = sizes;
    }

    /**
     * @return the colors
     */
    public String[] getColors() {
        return colors;
    }

    /**
     * @param colors the colors to set
     */
    public void setColors(String[] colors) {
        this.colors = colors;
    }
    private OrderController controller ;

    /**
     *
     */
    public Image image;
    private Integer orgWidth;
    private Integer orgHeight;
    private Integer scaledWidth;
    private Integer scaleHeight;
    private String imagefile;
    private Boolean canOpen = false;
    private Product product;
    private String[] sizes = new String[0];
    private String[] colors = new String[0];
    MediaTracker tracker;// w  w w.d  e  m o 2s  .c o  m
    Thread motor;
    final String imageFolder = ".\\resources\\productsimages\\";

    /**
     *
     * @param product
     * @param controller
     */
    public PanelOrder(Product product, OrderController controller ) {
        this.product = product;
        this.controller = controller ;
        imagefile = String.format("%s%s.jpg", imageFolder, product.getId());
        if (product instanceof Clothing) {
            this.sizes = ((Clothing) product).getSizes().toArray( new String[0]) ;
            this.colors = ((Clothing) product).getColors().toArray( new String[0]) ;
        }
        else
        {
            this.sizes = new String[0] ;
            this.colors = new String[0];
        }
        initComponents();
        if( ! (product instanceof Clothing) ) {
            lblSize.setVisible(false);
            cboSize.setVisible(false);
            lblColor.setVisible(false);
            cboColor.setVisible(false);
        }        
        
        lblTitle.setText(product.getName());
        motor = new Thread(this);
        motor.setPriority(Thread.MIN_PRIORITY);
        motor.start();
        spnQty.setValue(1);
        this.getbtnAdd().addActionListener(oc);
    }

    /**
     * Creates new form PanelPic
     */
    public PanelOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        panelInput = new javax.swing.JPanel();
        lblSize = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        lblColor = new javax.swing.JLabel();
        cboColor = new javax.swing.JComboBox<>();
        lblQty = new javax.swing.JLabel();
        spnQty = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        panelTitle.setAlignmentX(1.0F);
        panelTitle.setFocusable(false);
        panelTitle.setPreferredSize(new java.awt.Dimension(517, 40));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("This is the title of the product");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setPreferredSize(new java.awt.Dimension(186, 25));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        panelInput.setPreferredSize(new java.awt.Dimension(517, 50));

        lblSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSize.setText("Size:");
        panelInput.add(lblSize);

        cboSize.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboSize.setModel(new DefaultComboBoxModel(getSizes()));
        cboSize.setAlignmentY(1.0F);
        cboSize.setPreferredSize(new java.awt.Dimension(75, 28));
        cboSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSizeActionPerformed(evt);
            }
        });
        panelInput.add(cboSize);

        lblColor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblColor.setText("Color:");
        lblColor.setAlignmentY(1.0F);
        panelInput.add(lblColor);

        cboColor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cboColor.setModel(new DefaultComboBoxModel(getColors()));
        cboColor.setPreferredSize(new java.awt.Dimension(120, 28));
        panelInput.add(cboColor);

        lblQty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQty.setText("Quantity:");
        panelInput.add(lblQty);

        spnQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, 20, 1));
        spnQty.setMinimumSize(new java.awt.Dimension(50, 20));
        spnQty.setPreferredSize(new java.awt.Dimension(50, 28));
        panelInput.add(spnQty);

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setPreferredSize(new java.awt.Dimension(75, 28));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelInput.add(btnAdd);

        btnClose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(75, 28));
        panelInput.add(btnClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void cboSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSizeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
            // TODO add your handling code here:
            controller.actionPerformed(evt);
    }//GEN-LAST:event_btnAddActionPerformed

    @Override
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (this.image == null) {
            return;
        }
        orgWidth = this.image.getWidth(null);
        orgHeight = this.image.getHeight(null);
        Graphics2D g2d = (Graphics2D) g;
        calculateScaledImage();
        Integer left = (this.getWidth() - scaledWidth) / 2;
        g2d.drawImage(this.image, left, 50, scaledWidth, scaleHeight, null);
    }

    private void calculateScaledImage() {
        float scaleFactor;
        if (orgWidth < orgHeight) {
            // fit Height
            scaleFactor = (float) orgHeight / (this.getHeight() - 140);

        } else {
            scaleFactor = (float) orgWidth / (this.getWidth() - 140);
        }
        scaleHeight = Math.round(orgHeight / scaleFactor);
        scaledWidth = Math.round(orgWidth / scaleFactor);

    }

    @Override
    public void run() {
        this.image = new ImageIcon(this.imagefile).getImage();
        this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JComboBox<String> cboColor;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JSpinner spnQty;
    // End of variables declaration//GEN-END:variables
}
